In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr.sum()

np.int64(21)

In [6]:
arr.mean()

np.float64(3.5)

In [7]:
arr.max()

np.int64(6)

In [8]:
arr.min()

np.int64(1)

In [26]:
arr1 = np.array([
    [18,29,32,40,56],
    [10,20,30,40,50],
    [12,34,56,78,90],
    [45,65,75,85,15]
])
arr1

array([[18, 29, 32, 40, 56],
       [10, 20, 30, 40, 50],
       [12, 34, 56, 78, 90],
       [45, 65, 75, 85, 15]])

In [13]:
arr1.sum()

np.int64(880)

In [ ]:
arr1.sum(axis=0) #column wise

array([ 85, 148, 193, 243, 211])

In [18]:
arr1.sum(axis=1) #row wise

array([175, 150, 270, 285])

In [29]:
arr1.mean(axis=0)

array([21.25, 37.  , 48.25, 60.75, 52.75])

In [30]:
arr1.mean(axis=1)

array([35., 30., 54., 57.])

In [19]:
arr1.max()

np.int64(90)

In [20]:
arr1.max(axis=0)

array([45, 65, 75, 85, 90])

In [21]:
arr1.max(axis=1)

array([56, 50, 90, 85])

In [22]:
arr1.min()

np.int64(10)

In [27]:
arr1.min(axis=0)

array([10, 20, 30, 40, 15])

In [32]:
arr_new = np.array([200,210,220,230,240,250,260])

In [34]:
np.median(arr_new)

np.float64(230.0)

In [35]:
np.percentile(arr_new, 50)

np.float64(230.0)

In [36]:
np.percentile(arr_new, 30)

np.float64(218.0)