In [1]:
import numpy as np

In [ ]:
arr = np.ones((2,3),dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.ones((5,),int)

array([1, 1, 1, 1, 1])

In [3]:
arr = np.ones((2,2,3,4))
arr

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [26]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])

arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.arange(1,21,1).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
np.linspace(1, 10, 20).reshape(4, 5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [1]:
from numpy.random import default_rng
import numpy as np

In [9]:
rng = default_rng(13)
rng.random(5)

array([0.86479759, 0.85530251, 0.8110234 , 0.26144636, 0.07719946])

In [19]:
rng.integers(1, 101, size=5)

array([60, 70, 97, 29, 12])

In [21]:
rng.normal(loc=50, scale=10, size=5)

array([41.94439955, 46.57199985, 60.51125143, 58.90839446, 47.37868537])

In [22]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
rng = default_rng(23)
rng.random(9).reshape(3,3)

array([[0.69393308, 0.64145822, 0.12864422],
       [0.11370805, 0.65334552, 0.85345711],
       [0.20177913, 0.21801864, 0.71658464]])