In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr.sum()

np.int64(21)

In [6]:
arr.mean()

np.float64(3.5)

In [7]:
arr.max()

np.int64(6)

In [8]:
arr.min()

np.int64(1)

In [26]:
arr1 = np.array([
    [18,29,32,40,56],
    [10,20,30,40,50],
    [12,34,56,78,90],
    [45,65,75,85,15]
])
arr1

array([[18, 29, 32, 40, 56],
       [10, 20, 30, 40, 50],
       [12, 34, 56, 78, 90],
       [45, 65, 75, 85, 15]])

In [13]:
arr1.sum()

np.int64(880)

In [ ]:
arr1.sum(axis=0) #column wise

array([ 85, 148, 193, 243, 211])

In [18]:
arr1.sum(axis=1) #row wise

array([175, 150, 270, 285])

In [39]:
arr1.mean(axis=0)

array([21.25, 37.  , 48.25, 60.75, 52.75])

In [30]:
arr1.mean(axis=1)

array([35., 30., 54., 57.])

In [19]:
arr1.max()

np.int64(90)

In [20]:
arr1.max(axis=0)

array([45, 65, 75, 85, 90])

In [21]:
arr1.max(axis=1)

array([56, 50, 90, 85])

In [22]:
arr1.min()

np.int64(10)

In [27]:
arr1.min(axis=0)

array([10, 20, 30, 40, 15])

In [32]:
arr_new = np.array([200,210,220,230,240,250,260])

In [34]:
np.median(arr_new)

np.float64(230.0)

In [35]:
np.percentile(arr_new, 50)

np.float64(230.0)

In [36]:
np.percentile(arr_new, 30)

np.float64(218.0)

In [52]:
np.percentile(arr_new, [25,50,75])

array([215., 230., 245.])

In [41]:
dup_arr = np.array([12,34,12,12,56,78,34,56])
dup_arr

array([12, 34, 12, 12, 56, 78, 34, 56])

In [42]:
np.unique(dup_arr)

array([12, 34, 56, 78])

In [53]:
np.unique(dup_arr, return_counts=True)

(array([12, 34, 56, 78]), array([3, 2, 2, 1]))

In [46]:
arr_sq = np.array([144, 16, 36, 625])

np.sqrt(arr_sq)

array([12.,  4.,  6., 25.])

In [47]:
arr_dec = np.array([23.543222, 12.433322, 18.6543332])

np.round(arr_dec, 2)

array([23.54, 12.43, 18.65])

In [49]:
scores = np.array([34,56,12,90,23,34])
scores.sort()
scores

array([12, 23, 34, 34, 56, 90])

In [59]:
scores = np.array([34,56,12,90,23,34])
new_scores = np.sort(scores)
print(new_scores)
print(scores)

[12 23 34 34 56 90]
[34 56 12 90 23 34]


In [54]:
sales = np.array([230,340,560,660,560,340,230])
sales.std()

np.float64(161.1312052524974)

In [57]:
print(sales.argmax())
print(sales.argmin())

3
0


In [58]:
sales.cumsum()

array([ 230,  570, 1130, 1790, 2350, 2690, 2920])

In [60]:
ages = np.array([23,-20,-34,56,45,-31])
np.abs(ages)

array([23, 20, 34, 56, 45, 31])