In [1]:
import numpy as np

In [15]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr + 1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [4]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
arr + arr1

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [6]:
arr2 = np.array([
    [1],
    [2],
    [3]
])
arr2

array([[1],
       [2],
       [3]])

In [7]:
arr + arr2

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [16]:
arr3 = np.array([[1]])

In [17]:
arr + arr3

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [18]:
arr * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [19]:
arr - 1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr / 10

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2]])

In [21]:
marks = np.array([
    [45, 60 ,38, 70],
    [55, 48, 62, 40],
    [30, 75, 50, 66]
])
marks

array([[45, 60, 38, 70],
       [55, 48, 62, 40],
       [30, 75, 50, 66]])

In [22]:
avg_marks = np.average(marks, axis=0)
avg_marks

array([43.33333333, 61.        , 50.        , 58.66666667])

In [23]:
marks - avg_marks

array([[  1.66666667,  -1.        , -12.        ,  11.33333333],
       [ 11.66666667, -13.        ,  12.        , -18.66666667],
       [-13.33333333,  14.        ,   0.        ,   7.33333333]])

In [24]:
mul1 = np.array([1,2,3,4,5])
mul2 = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])

In [25]:
mul1 * mul2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [26]:
np.arange(1,6) * np.arange(1,6).reshape(5,1)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])