In [1]:
import numpy as np

In [2]:
arr = np.array([12,34,56,67,78,10,4,5,6])

In [3]:
arr[arr>30]

array([34, 56, 67, 78])

In [4]:
arr = np.array([
    [12,34,56,10],
    [90,56,20,10],
    [2,3,4,50]
])

In [5]:
arr[arr>30]

array([34, 56, 90, 56, 50])

In [7]:
arr[(arr > 10) & (arr < 50)]

array([12, 34, 20])

In [8]:
arr[(arr > 30) | (arr%4 == 0)]

array([12, 34, 56, 90, 56, 20,  4, 50])

In [11]:
names = np.array(["Vansh", "Aman", "Rahul", "Shiv", "Kartik"])
scores = np.array([34,56,78,90,65])

In [ ]:
names[scores > 60]

np.str_('Rahul')