In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([12,34,56,"45"])

array(['12', '34', '56', '45'], dtype='<U21')

In [6]:
np.array([12,34,56,False, True])

array([12, 34, 56,  0,  1])

In [7]:
np.array([23,45,67,90.3])

array([23. , 45. , 67. , 90.3])