In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([12,34,56,"45"])

array(['12', '34', '56', '45'], dtype='<U21')

In [6]:
np.array([12,34,56,False, True])

array([12, 34, 56,  0,  1])

In [7]:
np.array([23,45,67,90.3])

array([23. , 45. , 67. , 90.3])

In [13]:
arr = np.array([10,20,30,40,50])

print(arr.size)
print(arr.ndim)
print(arr.shape)

5
1
(5,)


In [15]:
arr = np.array([
    [10,20,30,40],
    [50,60,70,80]
    ])

print(arr.size)
print(arr.ndim)
print(arr.shape)

8
2
(2, 4)


In [17]:
arr = np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
])

print(arr.size)
print(arr.ndim)
print(arr.shape)

12
3
(2, 2, 3)
