In [1]:
import numpy as np

In [26]:
arr = np.arange(1,10)

print(arr)
print(arr[0])
print(arr[1])
print(arr[-1])

[1 2 3 4 5 6 7 8 9]
1
2
9


In [28]:
print(arr[0:4])
print(arr[:4])
print(arr[4:])
print(arr[0::2])
print(arr[-1::-1])
print(arr[::2])

[1 2 3 4]
[1 2 3 4]
[5 6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]


In [29]:
arr = np.arange(1,21).reshape(4,5)

print(arr)
print(arr[0][1])
print(arr[-1][-1])
print(arr[0,1])
print(arr[-1,-1])
print(arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2
20
2
20
8


In [50]:
print(arr)
print(arr[0:2])
print(arr[0:,1:4])
print(arr[:2, :2])
print(arr[-1::-1, -1::-1])
print(arr[:, -1])
print(arr[2:, 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[1 2]
 [6 7]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[ 5 10 15 20]
[[14 15]
 [19 20]]


In [51]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
arr[1:3, 1:3]

array([[ 7,  8],
       [12, 13]])

In [54]:
arr[2:, 3:4]

array([[14],
       [19]])