In [1]:
import numpy as np

In [3]:
arr = np.array([12,34,56,10,23,45,34,59,46,59])

In [4]:
arr[0] = 10
arr

array([10, 34, 56, 10, 23, 45, 34, 59, 46, 59])

In [5]:
arr[1:4] = [20,30,40]
arr

array([10, 20, 30, 40, 23, 45, 34, 59, 46, 59])

In [6]:
arr[arr == 59] = 60
arr

array([10, 20, 30, 40, 23, 45, 34, 60, 46, 60])

In [9]:
arr[[4,6]] = [25,35]
arr

array([10, 20, 30, 40, 25, 45, 35, 60, 46, 60])