In [1]:
import numpy as np

In [7]:
scores = np.array([34,56,89,12,20,5,10,45])
scores

array([34, 56, 89, 12, 20,  5, 10, 45])

In [6]:
scores.sort()
scores

array([ 5, 10, 12, 20, 34, 45, 56, 89])

In [8]:
sorted_scores = np.sort(scores)
print(sorted_scores)
print(scores)

[ 5 10 12 20 34 45 56 89]
[34 56 89 12 20  5 10 45]


In [17]:
arr = np.array([
    [12,34,56,10,5],
    [10,34,16,20,5],
    [120,40,50,10,52],
    [1,30,56,10,60]
])

arr

array([[ 12,  34,  56,  10,   5],
       [ 10,  34,  16,  20,   5],
       [120,  40,  50,  10,  52],
       [  1,  30,  56,  10,  60]])

In [13]:
arr.sort(axis=0)
arr

array([[  1,  30,  16,  10,   5],
       [ 10,  34,  50,  10,   5],
       [ 12,  34,  56,  10,  52],
       [120,  40,  56,  20,  60]])

In [16]:
arr.sort(axis=1)
arr

array([[  5,  10,  12,  34,  56],
       [  5,  10,  16,  20,  34],
       [ 10,  40,  50,  52, 120],
       [  1,  10,  30,  56,  60]])

In [18]:
arr

array([[ 12,  34,  56,  10,   5],
       [ 10,  34,  16,  20,   5],
       [120,  40,  50,  10,  52],
       [  1,  30,  56,  10,  60]])

In [19]:
np.sort(arr, axis=0)

array([[  1,  30,  16,  10,   5],
       [ 10,  34,  50,  10,   5],
       [ 12,  34,  56,  10,  52],
       [120,  40,  56,  20,  60]])

In [20]:
np.sort(arr, axis=1)

array([[  5,  10,  12,  34,  56],
       [  5,  10,  16,  20,  34],
       [ 10,  40,  50,  52, 120],
       [  1,  10,  30,  56,  60]])