In [1]:
import numpy as np

In [11]:
scores = np.array([45,23,40,20,15,78,5,90])
np.where(scores >= 40, 'Pass', 'Fail')

array(['Pass', 'Fail', 'Pass', 'Fail', 'Fail', 'Pass', 'Fail', 'Pass'],
      dtype='<U4')

In [8]:
arr = np.array([10,20,-3,-45,45,-4,-5,15,16])
np.where(arr<0, 0, arr)

array([10, 20,  0,  0, 45,  0,  0, 15, 16])

In [12]:
arr = np.array([45,67,89,103,110,34,56,90,100,78])
np.where(arr>100, 100, arr)

array([ 45,  67,  89, 100, 100,  34,  56,  90, 100,  78])

In [13]:
arr = np.array([23,13,25,67,34,10,18,17])
np.where(arr>=18, "Adult", "Child")

array(['Adult', 'Child', 'Adult', 'Adult', 'Adult', 'Child', 'Adult',
       'Child'], dtype='<U5')

In [15]:
scores = np.array([23,45,67,89,23,45,30,10])
np.where(scores < 40, scores+10, scores)

array([33, 45, 67, 89, 33, 45, 40, 20])

In [16]:
salary = np.array([30000,40000,20000,25000,150000,450000,50000,55000])
np.where(salary < 30000, salary + salary*0.2, salary + salary*0.1)

array([ 33000.,  44000.,  24000.,  30000., 165000., 495000.,  55000.,
        60500.])

In [24]:
battery = np.array([15,80,5,45,19,10])
is_charging = np.array([False,False,True,False,False,True])

np.where(is_charging, "Charging", np.where(battery < 20, "Charge Now", "OK"))

array(['Charge Now', 'OK', 'Charging', 'OK', 'Charge Now', 'Charging'],
      dtype='<U10')

In [48]:
yesterday = np.array([200, 150, 320, 90, 500, 75, 10])
today = np.array([215, 150, 310, 93, 500, 72, 8000])

change = (today - yesterday)/(yesterday * 100)
np.where(change > 5, "Big Jump", 
         np.where(change > 0, "Up", 
                  np.where(change < 0, "Down", "No Change")))

array(['Up', 'No Change', 'Down', 'Up', 'No Change', 'Down', 'Big Jump'],
      dtype='<U9')